refresh:
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.pu.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.mcf.sec27.png .
	# supervised graphs
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.pu.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.mcf.sec27.png .
	# jury_poste
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.pu.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.mcf.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.pu.sec26.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.mcf.sec26.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.pu.sec25.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.mcf.sec25.png .
