refresh:
	# sec 27 thesis jurys
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.pu.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.mcf.sec27.png .
	# sec 27 supervised graphs
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.pu.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.mcf.sec27.png .

	# sec 26 thesis jurys
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.sec26.png .
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.pu.sec26.png .
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.mcf.sec26.png .
	# sec 26 supervised graphs
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.sec26.png .
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.pu.sec26.png .
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.mcf.sec26.png .

	# sec 25 thesis jurys
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.sec25.png .
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.pu.sec25.png .
	cp ../../workpace/supervision-reviewing-jury/plots/examiner.mcf.sec25.png .
	# sec 25 supervised graphs
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.sec25.png .
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.pu.sec25.png .
	cp ../../workpace/supervision-reviewing-jury/plots/supervised.mcf.sec25.png .


	# jury_poste
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.pu.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.mcf.sec27.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.pu.sec26.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.mcf.sec26.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.pu.sec25.png .
	cp ../../workpace/supervision-reviewing-jury/plots/jury_poste.mcf.sec25.png .
